name: Build

on:
  # push:
  #   paths:
  #     - ".github/workflows/**"
  #     - "autotrace/**"
  #     - "**.py"
  #     - "**.toml"
  #     - "**.in"
  workflow_call:
  workflow_dispatch:

concurrency:
  group: build-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Extract GLib headers
        shell: bash
        run: >
          unzip ./third-party/autotrace/distribute/win/3rdparty/glib-dev_2.34.3-1_win64.zip
          -d ./third-party/glib

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Build source distribution
        run: uv build --sdist

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: ./dist/*.tar.gz

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Extract GLib headers
        shell: bash
        run: >
          unzip ./third-party/autotrace/distribute/win/3rdparty/glib-dev_2.34.3-1_win64.zip
          -d ./third-party/glib

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.3

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl

  merge_artifacts:
    name: Merge artifacts
    runs-on: ubuntu-latest
    needs:
      - build_sdist
      - build_wheels
    steps:
      - name: Merge artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: wheels
          pattern: wheels-*
          delete-merged: true
