name: Release

on:
  # push:
  #   tags:
  #     - v*
  workflow_call:

concurrency: release-${{ github.ref }}

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    name: Create release
    runs-on: ubuntu-latest
    environment: Release
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./dist

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: ./dist/*

  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    name: Publish package to PyPI
    runs-on: ubuntu-latest
    environment: Release
    permissions:
      id-token: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./dist

      - name: Upload distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
